version: "3.8"

services:
  redis:
    container_name: redis-cache
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - data:/data/db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  api:
    build:
      context: .
      target: production
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: yarn run start
    depends_on:
      - postgres
    environment:
      - PORT=3000

volumes:
  data: {}
